import {readFile,writeFile} from 'node:fs/promises';
const ids=['01-product-brief','02-mvp-scope','03-learning-content','04-architecture','05-roadmap-backlog','06-experiments','07-demo-guide','08-decisions','09-qa'];
const docs=await Promise.all(ids.map(async id=>({id,...Object.fromEntries(await Promise.all(['vi','en'].map(async lang=>[lang,await readFile(new URL(`../docs/${lang==='en'?'en/':''}${id}.md`,import.meta.url),'utf8')])))})));
await writeFile(new URL('../src/project-docs.js',import.meta.url),`// Generated by scripts/build-docs.mjs. Edit docs/*.md and docs/en/*.md.\nexport const projectDocs = ${JSON.stringify(docs,null,2)};\n`);
console.log(`Bundled ${docs.length} documents in Vietnamese and English.`);
